### ISSUE TITLE
Date values serialization

### ISSUE THREAD

**Issue by icflorescu** [AmpersandJS/ampersand-state#177] opened 2015-07-03 15:25 UTC
I've noticed Date value properties are internally kept as unix timestamp integers.

While this is transparent (as it should) for the user, I think they **should be serialized as valid [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) strings**, **not as integers**.

For instance, if we're setting a `date` property to `new Date('2015-07-01')`, calling `serialize()` should produce `'2015-07-01T00:00:00.000Z'`, not `1435708800000`.

I wonder why nobody bumped into this so far... especially since most server implementations will expect dates fo be formatted as valid ISO 8601 strings in JSON API calls...

For now, I am circumventing the problem by overriding my models' `serialize()`, but I don't think this should be the way to go.

If everybody agrees, I could make a PR to correct this.

Any thoughts?

**Comment by cdaringe** [comment] 2015-07-03 17:05
Yes, I agree that serialized date output should produce not just ISO 8601 compliant strings, but ISO compliant locale strings.  toISO will yield the value normalized to UTC, which is just as problematic as the status quo.  I'm sure that's what you inferred, but it is an important distinction. I [blogged on this](cdaringe.com/managing-application-dates/) recently

**Comment by icflorescu** [comment] 2015-07-03 20:50
AFAIK, the "standard" JS Date `.toJSON()` serialization is normalizing to UTC... which is not ideal, but it's still better than "serializing" to integers... and closer to a generally expected behavior.

Please make sure to update the URL to your post in the comment above, in case other people come across this thread (it should be [cdaringe.com/managing-application-dates/](http://cdaringe.com/managing-application-dates/) instead of [github.com/AmpersandJS/ampersand-state/issues/cdaringe.com/managing-application-dates/](https://github.com/AmpersandJS/ampersand-state/issues/cdaringe.com/managing-application-dates/) - probably got messed up by GitHub somehow).

I also use moment.js sometimes, for lots of reasons - TZ info just one of them, but most people are satisfied with keeping / serializing dates normalized to UTC. Arguably, the user TZ is a different kind of information, rather pertaining to where the user was located when a specific event occurred.

Meanwhile, since my server API is serializing dates like `2015-07-01T00:00:00.000Z` and expects my client to provide the same, here's what I do in a base `AbstractModel` (CoffeeScript):

    AmpersandModel = require 'ampersand-model'

    module.exports = AmpersandModel.extend
      serialize: ->
        attrs = AmpersandModel::serialize.apply @, arguments
        for own name, value of attrs when @_definition[name].type is 'date'
          attrs[name] = new Date(value).toJSON()
        return attrs

Would something like this be good enough to use as a standard in `apmersand-state`? At least it would be consistent with a generally expected behavior...

**Comment by prust** [comment] 2015-07-04 14:21
> the "standard" JS Date .toJSON() serialization is normalizing to UTC
> Arguably, the user TZ is a different kind of information

I agree. Over the past several years our company has written a large, soft real-time collaboration app (really a suite of 3 apps: Desktop, Mobile & Server) recording time/date information for a variety of functionality, some exposed to the user and some for our own back-end purposes. In all of this, there was only one situation where we weren't happy with storing timestamps in UTC and displaying them in the user's local timezone.

In that one situation, we had a manually-entered date field with no time information associated with it. If the user entered a date and we saved it as midnight, then when the user crossed a timezone the date would change, which wouldn't be the expected behavior. This could have been solved in at least 3 ways: 1) storing the date with the timezone information, 2) storing & displaying the dates as midnight UTC, 3) storing a date-only ISO representation (YYYY-MM-DD). We ended up going with option 3.

There are two non-negligible advantages to storing the dates in UTC: you can sort by them as strings and you can use less-than/greater-than filtering as strings, without needing to use date functions or convert them to date objects. Both of these make database queries simpler and faster.

OTOH, a different app that I'm working on now relies even more heavily on time data, so we will be storing the user's current timezone with each timestamp -- but we will store the timezone offset in a different field and continue storing the timestamps as UTC so that we can efficiently sort and filter them. We're not using the timezone information yet, but by storing it we're future-proofing our application.

Even though we were happy with ISO strings in our other application, this one does so much summing and diffing of times that we considered using Julian dates and in the end landed on Unix timestamps (but w/ millisecond precision). Storing our timestamps and timezone offsets as numbers allows not only sorting and filtering, but also summing and diffing, without needing to create date objects or use SQL date functions. Numbers aren't as human-readable, but human-readability can be a disadvantage in that it can tempt devs to do naive things with the strings (attempting to do manual diffs or simply not taking timezone into account).

All that to say that IMO different applications have different needs: some will want or need local timezone data, others will gain much efficiency & simplicity by using numeric date/time representations. But, all things considered, UTC ISO dates are a good default that fill most needs and since they are what you get when you do "new Date().toJSON()", they seem like the most expected, intuitive behavior.

**Comment by cdaringe** [comment] 2015-07-04 23:29
given that there is no _bug_ per se here, it's just user expectation differences, let's close this one out.  one of the best part of ampersandjs is its minimalist nature and great extensibility.  in this case, you can [create your own datatypes](https://github.com/AmpersandJS/ampersand-state#datatypes--ampersandstateextend-datatypes-mycustomtypes-) easily on top of ampersand state.  for this issue, i generated an [ampersand state datatype for locale iso-strings](https://github.com/cdaringe/ampersand-state-mixin-datatype-iso-date).  feel free to try the same per your needs.

@icflorescu, modifying `serialize` could work, but you may be best off creating a new datatype as well.

**Closed by cdaringe** 2015-07-04 23:29 UTC
